---

#     ____                       ___        __                     ______                   ___
#    /\  _`\              __    /\_ \      /\ \                   /\__  _\                 /\_ \
#    \ \ \L\ \   __  __  /\_\   \//\ \     \_\ \      __    _ __  \/_/\ \/    ___     ___  \//\ \      ____
#    \ \  _ <' /\ \/\ \ \/\ \    \ \ \    /'_` \   /'__`\ /\`'__\   \ \ \   / __`\  / __`\  \ \ \    /',__\
#     \ \ \L\ \\ \ \_\ \ \ \ \    \_\ \_ /\ \L\ \ /\  __/ \ \ \/     \ \ \ /\ \L\ \/\ \L\ \  \_\ \_ /\__, `\
#      \ \____/ \ \____/  \ \_\   /\____\\ \___,_\\ \____\ \ \_\      \ \_\\ \____/\ \____/  /\____\\/\____/
#       \/___/   \/___/    \/_/   \/____/ \/__,_ / \/____/  \/_/       \/_/ \/___/  \/___/   \/____/ \/___/
#
#      CzechPMDevs >>> BuilderTools
#
#     > Authors: VixikCZ, kaliiks
#     > Plugin linke WorldEdit for PocketMine-MP servers
#     > Version: 1.1.0
#
#     > Main configuration file
#
#


## \
### > Plugin Settings
## /

debug: true


## \
### > Commands
## /

# ClearInventory command:

# Copy command:

# Cube command:

# Decoration command:

# Draw command:

# Fill command:

# FirstPosition command:

# Fix command:

# Flip command:

# Help command:

# Hsphere command:

# Id command:

## Naturalize command:
naturalizer:

naturalize-force-fill: false
naturalize-save-undo: true
naturalize-dirt-count: [3, 5] # Count dirt blocks (random -> [min - 4, max -5])

...