---

#     ____                       ___        __                     ______                    ___
#    /\  _`\              __    /\_ \      /\ \                   /\__  _\                  /\_ \
#    \ \ \L\ \   __  __  /\_\   \//\ \     \_\ \      __    _ __  \/_/\ \/    ___     ___   \//\ \      ____
#    \ \  _ <' /\ \/\ \ \/\ \    \ \ \    /'_` \   /'__`\ /\`'__\   \ \ \   / __`\  / __`\   \ \ \    /',__\
#     \ \ \L\ \\ \ \_\ \ \ \ \    \_\ \_ /\ \L\ \ /\  __/ \ \ \/     \ \ \ /\ \L\ \/\ \L\ \   \_\ \_ /\__, `\
#      \ \____/ \ \____/  \ \_\   /\____\\ \___,_\\ \____\ \ \_\      \ \_\\ \____/\ \____/   /\____\\/\____/
#       \/___/   \/___/    \/_/   \/____/ \/__,_ / \/____/  \/_/       \/_/ \/___/  \/___/    \/____/ \/___/
#
#      CzechPMDevs >>> BuilderTools
#
#     > Authors: VixikCZ, kaliiks
#     > Plugin linke WorldEdit for PocketMine-MP servers
#     > Version: 1.1.0
#
#     > Main configuration file
#
#


### Draw command:
minBrush: 1
maxBrush: 6

# Undo command:
use-undo: true


...