---

#     ____                       ___        __                     ______                   ___
#    /\  _`\              __    /\_ \      /\ \                   /\__  _\                 /\_ \
#    \ \ \L\ \   __  __  /\_\   \//\ \     \_\ \      __    _ __  \/_/\ \/    ___     ___  \//\ \      ____
#    \ \  _ <' /\ \/\ \ \/\ \    \ \ \    /'_` \   /'__`\ /\`'__\   \ \ \   / __`\  / __`\  \ \ \    /',__\
#     \ \ \L\ \\ \ \_\ \ \ \ \    \_\ \_ /\ \L\ \ /\  __/ \ \ \/     \ \ \ /\ \L\ \/\ \L\ \  \_\ \_ /\__, `\
#      \ \____/ \ \____/  \ \_\   /\____\\ \___,_\\ \____\ \ \_\      \ \_\\ \____/\ \____/  /\____\\/\____/
#       \/___/   \/___/    \/_/   \/____/ \/__,_ / \/____/  \/_/       \/_/ \/___/  \/___/   \/____/ \/___/
#
#      CzechPMDevs >>> BuilderTools
#
#     > Authors: VixikCZ, kaliiks
#     > Plugin linke WorldEdit for PocketMine-MP servers
#     > Version: 1.1.0
#
#     > Main configuration file
#
#


## \
### > Plugin Settings
## /

config-version: 1.1.0

debug: true

## \
### > Editors
## /

copier:
  # Saves undo at //paste, //flip and //rotate
  save-undo: true

canceller:
  # Saves undo at //redo
  save-undo: true
  # Saves redo at //undo
  save-redo: true

fixer:
  # Saves undo at //fix
  save-undo: true
  # Remove heads when //fix
  remove-heads: true
  # Fix tiles NBT (Chest, ...)
  fix-tiles: true
  added-blocks: [] # How to add blocks? Look at the wiki (https://github.com/CzechPMDevs/BuilderTools/wiki)!


naturalizer:
  force-fill: false
  # Saves undo at //naturalize
  save-undo: true
  # Count of dirt blocks (random -> [min - 3, max - 5])
  dirt-count: [3, 5]

...