---

#     ____                       ___        __                     ______                   ___
#    /\  _`\              __    /\_ \      /\ \                   /\__  _\                 /\_ \
#    \ \ \L\ \   __  __  /\_\   \//\ \     \_\ \      __    _ __  \/_/\ \/    ___     ___  \//\ \      ____
#    \ \  _ <' /\ \/\ \ \/\ \    \ \ \    /'_` \   /'__`\ /\`'__\   \ \ \   / __`\  / __`\  \ \ \    /',__\
#     \ \ \L\ \\ \ \_\ \ \ \ \    \_\ \_ /\ \L\ \ /\  __/ \ \ \/     \ \ \ /\ \L\ \/\ \L\ \  \_\ \_ /\__, `\
#      \ \____/ \ \____/  \ \_\   /\____\\ \___,_\\ \____\ \ \_\      \ \_\\ \____/\ \____/  /\____\\/\____/
#       \/___/   \/___/    \/_/   \/____/ \/__,_ / \/____/  \/_/       \/_/ \/___/  \/___/   \/____/ \/___/
#
#      CzechPMDevs >>> BuilderTools
#
#     > Authors: VixikCZ, kaliiks
#     > Plugin linke WorldEdit for PocketMine-MP servers
#     > Version: 1.1.0
#
#     > Main configuration file
#
#


## \
### > Plugin Settings
## /

config-version: 1.1.0

debug: true

## \
### > Commands
## /

# Copy command:
copier:
  save-undo: true

# Cube command:

# Decoration command:

# Draw command:

# Fill command:

# FirstPosition command:

# Fix command:
fixer:
  save-undo: true
  remove-heads: true
  fix-tiles: true
  added-blocks: [] # How to add blocks? Look at the wiki (https://github.com/CzechPMDevs/BuilderTools/wiki)!

# Flip command:

# Help command:

# Hsphere command:

# Id command:

## Naturalize command:
naturalizer:
  force-fill: false
  save-undo: true # Adding step to //undo
  dirt-count: [3, 5] # Count dirt blocks (random -> [min - 4, max -5])

...